@url = http://localhost:3000

###
GET  {{url}}/category
###
GET  {{url}}/category/9f7b6d33-e217-4ff2-b75f-7dfb69996b13
###
GET  {{url}}/category/9f7b6d33-e217-4ff2-b75f-7dfb69996b13/books

###
POST {{url}}/category
Content-Type: application/json

{
 "name":"crime-related",
 "description":"This are crime related books"
}