@url=http:localhost:3000

###
GET  {{url}}/books
###
GET  {{url}}/books/c9cad6c8-2781-4fca-b6db-fd8da1a15408
###
GET  {{url}}/books/c9cad6c8-2781-4fca-b6db-fd8da1a15408/reviews

###
POST {{url}}/books
Content-Type: application/json

{
  "title":"My in crime",
  "description":"The book is about personal life related to John Kiriamiti before he went to prison",
  "publicationYear":1985,
  "author":"70cb0242-4700-45b9-a188-eae9aaaecfe2",
  "category":"9f7b6d33-e217-4ff2-b75f-7dfb69996b13"
}

### 
PATCH {{url}}/books/c9cad6c8-2781-4fca-b6db-fd8da1a15408
Content-Type: application/json

{
  "publicationYear":1981
}

###
DELETE {{url}}/books/c9cad6c8-2781-4fca-b6db-fd8da1a15408