@url=http://localhost:3000

###
GET {{url}}/authors
###
POST {{url}}/authors
Content-Type: application/json

{
  "name":"Ngũgĩ wa Thiong'o",
  "bio":"One of Africa’s most celebrated writers, known for his novels, plays, and essays, often writing in Gikuyu and English.",
  "birthDate":"1980-12-12"
}

###
PATCH  {{url}}/authors/97a9c6be-02f7-427f-8328-45b749afafd2
Content-Type: application/json

{
  "birthDate":"1976-12-12"
}
###
DELETE {{url}}/authors/97a9c6be-02f7-427f-8328-45b749afafd2
